export const getCategoryList=()=>{
    
}

export const categoryList=[
    {
        name:'食品',
        id:'shiping',
        children:[
            {
                name:'休闲零食',
                id:'xiuxianlingshi',
                children:[
                    {
                        name:'糖果',
                        id:'tangguo',
                        img:''
                    },
                    {
                        name:'辣条豆干',
                        id:'natiaodougan',
                        img:''
                    },
                    {
                        name:'零食大礼包',
                        id:'lingshidalibao',
                        img:''
                    },
                    {
                        name:'巧克力',
                        id:'qiaokeli',
                        img:''
                    },
                    {
                        name:'海味零食',
                        id:'haiweilingshi',
                        img:''
                    }
                ]
            },
            {
                name:'粮油调味',
                id:'粮油调味',
                children:[
                    {
                        name:'面粉',
                        id:'mianfen',
                        img:''
                    },
                    {
                        name:'烘培原料',
                        id:'烘培原料',
                        img:''
                    },
                    {
                        name:'米',
                        id:'mi',
                        img:''
                    },
                    {
                        name:'花生菜籽油',
                        id:'huashengcaiziyou',
                        img:''
                    },
                    {
                        name:'五谷杂粮',
                        id:'五谷杂粮',
                        img:''
                    }
                ]
            },
            {
                name:'乳品饮料',
                id:'rupingyinliao',
                children:[
                    {
                        name:'纯牛奶',
                        id:'chunniunai',
                        img:''
                    },
                    {
                        name:'饮用水',
                        id:'yinyongshui',
                        img:''
                    },
                    {
                        name:'冰淇淋',
                        id:'bingqiling',
                        img:''
                    },
                    {
                        name:'气泡水',
                        id:'qipaoshui',
                        img:''
                    },
                    {
                        name:'碳酸饮料',
                        id:'tanshuanyingliao',
                        img:''
                    }
                ]
            },

        ]
    },
    {
        name:'电器',
        id:'dianqi',
        children:[
            {
                name:'中式厨电',
                id:'zhongshichudian',
                children:[
                    {
                        name:'电吹风',
                        id:'dianchuifeng',
                        img:''
                    },
                    {
                        name:'微波炉',
                        id:'weibolu',
                        img:''
                    },
                    {
                        name:'电饭煲',
                        id:'dianfanbao',
                        img:''
                    },
                    {
                        name:'除湿器',
                        id:'chushiqi',
                        img:''
                    },
                ]
            },
            {
                name:'西式厨电',
                id:'xishichudian',
                children:[
                    {
                        name:'',
                        id:'',
                        img:''
                    }
                ]
            },
            {
                name:'大家电',
                id:'dajiadian',
                children:[
                    {
                        name:'',
                        id:'',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'女装',
        id:'nvzhuang',
        children:[
            {
                name:'热卖选购',
                id:'remaixuangou',
                children:[
                    {
                        name:'T恤',
                        id:'txu',
                        img:''
                    },
                    {
                        name:'连衣裙',
                        id:'lianyiqun',
                        img:''
                    },
                    {
                        name:'休闲裤',
                        id:'xiuxianku',
                        img:''
                    },
                    {
                        name:'衬衫',
                        id:'chenshan',
                        img:''
                    },{
                        name:'牛仔裤',
                        id:'niuziaku',
                        img:''
                    }
                ]
            },
            {
                name:'女士上衣',
                id:'nvshishangyi',
                children:[
                    {
                        name:'针织衫',
                        id:'zhenzhishan',
                        img:''
                    },
                    {
                        name:'背心',
                        id:'beixin',
                        img:''
                    },
                    {
                        name:'毛衣',
                        id:'maoyi',
                        img:''
                    },
                    {
                        name:'雪纺衫',
                        id:'xuefangshan',
                        img:''
                    },{
                        name:'卫衣',
                        id:'weiyi',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'美妆',
        id:'meizhuang',
        children:[
            {
                name:'面部护肤',
                id:'mainbuhufu',
                children:[
                    {
                        name:'面膜',
                        id:'mianmo',
                        img:''
                    },
                    {
                        name:'化妆水',
                        id:'huazhuangshui',
                        img:''
                    },
                    {
                        name:'眼霜',
                        id:'yanshuang',
                        img:''
                    },
                    {
                        name:'润唇膏',
                        id:'runchungao',
                        img:''
                    },
                    {
                        name:'卸妆',
                        id:'xiezhuang',
                        img:''
                    }
                ]
            },
            {
                name:'彩妆',
                id:'caizhuang',
                children:[
                    {
                        name:'眼线笔',
                        id:'ytanxianbi',
                        img:''
                    },
                    {
                        name:'眼影',
                        id:'眼影',
                        img:''
                    },
                    {
                        name:'粉饼',
                        id:'粉饼',
                        img:''
                    },
                    {
                        name:'睫毛膏',
                        id:'jiemaogao',
                        img:''
                    },
                    {
                        name:'bb霜',
                        id:'bbshaung',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'母婴',
        id:'muying',
        children:[
            {
                name:'尿裤',
                id:'niaoku',
                children:[
                    {
                        name:'婴儿纸尿片',
                        id:'yingerzhiliaopian',
                        img:''
                    },
                    {
                        name:'成人尿裤',
                        id:'成人尿裤',
                        img:''
                    },
                    {
                        name:'宝宝纸尿裤',
                        id:'baobaozhiliaopian',
                        img:''
                    }
                ]
            },
            {
                name:'玩具乐器',
                id:'wanjuyueqi',
                children:[
                    {
                        name:'积木',
                        id:'jimu',
                        img:''
                    },
                    {
                        name:'毛绒玩具',
                        id:'maorongwanju',
                        img:''
                    },
                    {
                        name:'遥控电动',
                        id:'yaokongdiandong',
                        img:''
                    }
                ]
            },
            {
                name:'洗护用品',
                id:'xihuyongpin',
                children:[
                    {
                        name:'棉柔巾',
                        id:'mianroujing',
                        img:''
                    },
                    {
                        name:'洗发沐浴',
                        id:'xifamuyu',
                        img:''
                    },
                    {
                        name:'口腔清洁',
                        id:'kouqiangqingjie',
                        img:''
                    },
                    {
                        name:'奶瓶',
                        id:'naiping',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'鞋包',
        id:'xiebao',
        children:[
            {
                name:'时尚女装',
                id:'shishangnvzhuang',
                children:[
                    {
                        name:'女靴',
                        id:'nvxue',
                        img:''
                    },
                    {
                        name:'凉鞋',
                        id:'liangxie',
                        img:''
                    },
                    {
                        name:'拖鞋',
                        id:'tuoxie',
                        img:''
                    },
                    {
                        name:'帆布鞋',
                        id:'fanbuxie',
                        img:''
                    }
                ]
            },
            {
                name:'潮流男鞋',
                id:'chaoliunanxie',
                children:[
                    {
                        name:'男士拖鞋',
                        id:'nanshituoxir',
                        img:''
                    },
                    {
                        name:'皮鞋',
                        id:'pixie',
                        img:''
                    },
                    {
                        name:'运动鞋',
                        id:'yundongxie',
                        img:''
                    },
                    {
                        name:'功能鞋',
                        id:'gongnengxie',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'办公',
        id:'bangong',
        children:[
            {
                name:'网络产品',
                id:'wangluochanping',
                children:[
                    {
                        name:'路由器',
                        id:'luyouqi',
                        img:''
                    },
                    {
                        name:'网络配件',
                        id:'wangluopeijian',
                        img:''
                    },
                    {
                        name:'交换机',
                        id:'jaohuanji',
                        img:''
                    },
                    {
                        name:'网线',
                        id:'wangxian',
                        img:''
                    },
                    {
                        name:'网卡',
                        id:'wangka',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'家装',
        id:'jiazhuang',
        children:[
            {
                name:'厨房卫浴',
                id:'chufangweiyu',
                children:[
                    {
                        name:'厨卫配件',
                        id:'chuweipeijian',
                        img:''
                    },
                    {
                        name:'淋浴花洒',
                        id:'lingyuhuasa',
                        img:''
                    },
                    {
                        name:'龙头',
                        id:'longtou',
                        img:''
                    },
                    {
                        name:'浴室柜',
                        id:'yushigui',
                        img:''
                    },
                    {
                        name:'排气扇',
                        id:'paiqishan',
                        img:''
                    },
                    {
                        name:'厨卫挂件',
                        id:'chuweiguajian',
                        img:''
                    },
                    
                ]
            },
            {
                name:'灯饰照明',
                id:'dengshizhaoming',
                children:[
                    {
                        name:'台灯',
                        id:'taideng',
                        img:''
                    },
                    {
                        name:'吸顶灯',
                        id:'xidingdeng',
                        img:''
                    },
                    {
                        name:'氛围照明',
                        id:'fenweizhaoming',
                        img:''
                    },
                    {
                        name:'LED灯源',
                        id:'dengyuan',
                        img:''
                    },
                    {
                        name:'射灯',
                        id:'shedeng',
                        img:''
                    },
                    {
                        name:'庭院灯',
                        id:'tingyuandeng',
                        img:''
                    },
                    
                ]
            }
        ]
    },
    {
        name:'图书',
        id:'tushu',
        children:[
            {
                name:'童书',
                id:'tongshu',
                children:[
                    {
                        name:'动漫/卡通',
                        id:'dongman',
                        img:''
                    },
                    {
                        name:'幼儿启蒙',
                        id:'youerqimeng',
                        img:''
                    },
                    {
                        name:'智力开发',
                        id:'zhilikafa',
                        img:''
                    },
                    {
                        name:'儿童文学',
                        id:'ertongwenxue',
                        img:''
                    }
                ]
            },
            {
                name:'考试教育',
                id:'kaoshijiaoyu',
                children:[
                    {
                        name:'外语学习',
                        id:'waiyuxuexi',
                        img:''
                    },
                    {
                        name:'大专教材',
                        id:'dazhaunjiaocai',
                        img:''
                    },
                    {
                        name:'杂志/期刊',
                        id:'zazhi',
                        img:''
                    },
                    {
                        name:'雅思',
                        id:'yasi',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'生鲜',
        id:'shengxian',
        children:[
            {
                name:'水果',
                id:'shuiguo',
                children:[
                    {
                        name:'榴莲',
                        id:'niulian',
                        img:''
                    },
                    {
                        name:'橙子',
                        id:'chengzi',
                        img:''
                    },
                    {
                        name:'奇异果',
                        id:'qiyiguo',
                        img:''
                    },
                    {
                        name:'蓝莓',
                        id:'lanmei',
                        img:''
                    },{
                        name:'芒果',
                        id:'mangguo',
                        img:''
                    },
                    {
                        name:'橘子',
                        id:'juzi',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'车品',
        id:'cheping',
        children:[
            {
                name:'汽车装饰',
                id:'qichezhuangshi',
                children:[
                    {
                        name:'钥匙扣',
                        id:'yaoshikou',
                        img:''
                    },
                    {
                        name:'停车牌',
                        id:'tingchepai',
                        img:''
                    },
                    {
                        name:'车贴',
                        id:'chetie',
                        img:''
                    },
                    {
                        name:'汽车脚垫',
                        id:'qichejiaodian',
                        img:''
                    },
                    {
                        name:'车载香水',
                        id:'chezaixiangshui',
                        img:''
                    },
                    {
                        name:'收纳袋',
                        id:'shounadai',
                        img:''
                    }
                ]
            },
            {
                name:'摩托/电动车',
                id:'motuo',
                children:[
                    {
                        name:'摩托车手套',
                        id:'motuocheshoutao',
                        img:''
                    },
                    {
                        name:'摩托车头盔',
                        id:'motuochetoukui',
                        img:''
                    },
                    {
                        name:'摩托车护具',
                        id:'motuochehuju',
                        img:''
                    },
                    {
                        name:'雨衣',
                        id:'yuyi',
                        img:''
                    },
                    {
                        name:'电动车装备',
                        id:'diandongchezhuangbei',
                        img:''
                    },
                    {
                        name:'电动车配件',
                        id:'diandongchepeijian',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'家纺',
        id:'jiafang',
        children:[
            {
                name:'家具布艺',
                id:'jiajubuyi',
                children:[
                    {
                        name:'地垫',
                        id:'didian',
                        img:''
                    },
                    {
                        name:'抱枕',
                        id:'baozhen',
                        img:''
                    },
                    {
                        name:'浴巾',
                        id:'yujing',
                        img:''
                    },
                    {
                        name:'坐垫',
                        id:'zuodian',
                        img:''
                    },
                    {
                        name:'洗脸巾',
                        id:'xilianjing',
                        img:''
                    },
                    {
                        name:'地毯',
                        id:'ditan',
                        img:''
                    },
                ]
            },
            {
                name:'床上用品',
                id:'chuangshangyongpin',
                children:[
                    {
                        name:'四件套',
                        id:'sijiantao',
                        img:''
                    },
                    {
                        name:'床垫',
                        id:'chuangdian',
                        img:''
                    },
                    {
                        name:'蚊帐',
                        id:'wenzhang',
                        img:''
                    },
                    {
                        name:'毛毯',
                        id:'maotan',
                        img:''
                    },
                    {
                        name:'床单',
                        id:'chuangdan',
                        img:''
                    },
                    {
                        name:'空调被',
                        id:'空调背',
                        img:''
                    },
                ]
            }
        ]
    },
    {
        name:'宠物',
        id:'chongwu',
        children:[
            {
                name:'猫猫',
                id:'maomao',
                children:[
                    {
                        name:'猫玩具',
                        id:'maowanju',
                        img:''
                    },
                    {
                        name:'猫猫美容',
                        id:'meirong',
                        img:''
                    },
                    {
                        name:'猫包',
                        id:'maobao',
                        img:''
                    },
                    {
                        name:'猫项圈',
                        id:'xiangquan',
                        img:''
                    },
                    {
                        name:'猫零食',
                        id:'lingshi',
                        img:''
                    }
                ]
            },
            {
                name:'狗狗',
                id:'gougou',
                children:[
                    {
                        name:'狗玩具',
                        id:'gouwanju',
                        img:''
                    },
                    {
                        name:'狗美容',
                        id:'meirong',
                        img:''
                    },
                    {
                        name:'狗包',
                        id:'maobao',
                        img:''
                    },
                    {
                        name:'狗项圈',
                        id:'xiangquan',
                        img:''
                    },
                    {
                        name:'狗零食',
                        id:'lingshi',
                        img:''
                    }
                ]
            }
        ]
    },
    {
        name:'百货',
        id:'baihuo',
        children:[
            {
                name:'酒具',
                id:'jiuju',
                children:[
                    {
                        name:'保温杯',
                        id:'baowenbei',
                        img:''
                    },
                    {
                        name:'塑料杯',
                        id:'suliaobei',
                        img:''
                    },
                    {
                        name:'玻璃杯',
                        id:'bolibei',
                        img:''
                    },
                   
                    {
                        name:'茶壶',
                        id:'chahu',
                        img:''
                    },
                    {
                        name:'保温杯',
                        id:'baowenbei',
                        img:''
                    },
                ]
            }
        ]
    },
    {
        name:'数码',
        id:'shuma',
        children:[
            {
                name:'影音娱乐',
                id:'yingyinyule',
                children:[
                    {
                        name:'收音机',
                        id:'shouyingji',
                        img:''
                    },
                    {
                        name:'MP3',
                        id:'mp3',
                        img:''
                    },
                    {
                        name:'音频',
                        id:'yinping',
                        img:''
                    },
                    {
                        name:'麦克风',
                        id:'maikefeng',
                        img:''
                    }
                ]
            },
            {
                name:'智能设备',
                id:'zhinengshebei',
                children:[
                    {
                        name:'智能手环',
                        id:'zhinengshouhuan',
                        img:''
                    },
                    {
                        name:'监控设备',
                        id:'jiankongshebei',
                        img:''
                    },
                    {
                        name:'无人机',
                        id:'wurenji',
                        img:''
                    },
                    {
                        name:'智能家居',
                        id:'zhinengjiaju',
                        img:''
                    }
                ]
            }
        ]
    }
   
]